# Generated by Django 6.0.4 on 2026-04-08 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ELEC', 'Ответственный за электрохозяйство'), ('FIRE', 'Ответственный за пожарную безопасность')], max_length=10, verbose_name='Вид ответственности')),
                ('electrical_group', models.IntegerField(blank=True, help_text='Только для электробезопасности', null=True, verbose_name='Группа по ЭБ')),
                ('order_number', models.CharField(blank=True, max_length=50, verbose_name='№ приказа о назначении')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_until', models.DateField(verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Ответственная роль',
                'verbose_name_plural': 'Ответственные роли',
            },
        ),
    ]
