# Generated by Django 6.0.4 on 2026-04-08 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Подразделение / Цех / Отдел')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Должность / Профессия')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='employees.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('hire_date', models.DateField(verbose_name='Дата приёма')),
                ('is_active', models.BooleanField(default=True, verbose_name='В штате')),
                ('exempt_primary_briefing', models.BooleanField(default=False, verbose_name='Освобождён от первичного инструктажа')),
                ('exempt_internship', models.BooleanField(default=False, verbose_name='Не требуется стажировка на рабочем месте')),
                ('exempt_ot_training', models.BooleanField(default=False, verbose_name='Освобождён от обучения по ОТ')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.position')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['position__department', 'position', 'last_name'],
            },
        ),
    ]
