# Generated by Django 6.0.4 on 2026-04-08 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionTrainingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OT', 'Охрана труда (Программы А/Б)'), ('PP_P', 'Первая помощь пострадавшим (ППП)'), ('SIZ', 'Использование СИЗ'), ('ELEC', 'Электробезопасность'), ('FIRE', 'Пожарная безопасность')], max_length=10, verbose_name='Категория')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_trainings', to='employees.position')),
            ],
            options={
                'verbose_name': 'Требование к должности',
                'verbose_name_plural': 'Требования к должностям',
                'unique_together': {('position', 'category')},
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OT', 'Охрана труда (Программы А/Б)'), ('PP_P', 'Первая помощь пострадавшим (ППП)'), ('SIZ', 'Использование СИЗ'), ('ELEC', 'Электробезопасность'), ('FIRE', 'Пожарная безопасность')], max_length=10, verbose_name='Категория обучения')),
                ('provider', models.CharField(choices=[('EMPLOYER', 'Работодатель'), ('CENTER', 'Учебный центр')], max_length=10, verbose_name='Кто проводил обучение')),
                ('training_date', models.DateField(verbose_name='Дата обучения')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Действительно до')),
                ('certificate', models.CharField(blank=True, max_length=100, verbose_name='№ протокола/удостоверения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Запись об обучении',
                'verbose_name_plural': 'Записи об обучении',
                'ordering': ['employee', 'category'],
                'unique_together': {('employee', 'category')},
            },
        ),
    ]
