# Generated by Django 6.0.4 on 2026-04-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingrecord',
            options={'ordering': ['employee', '-training_date'], 'verbose_name': 'Запись об обучении', 'verbose_name_plural': 'Записи об обучении'},
        ),
        migrations.AlterUniqueTogether(
            name='positiontrainingrequirement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trainingrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивная запись'),
        ),
        migrations.AddConstraint(
            model_name='positiontrainingrequirement',
            constraint=models.UniqueConstraint(fields=('position', 'category'), name='unique_position_training_req'),
        ),
        migrations.AddConstraint(
            model_name='trainingrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'category', 'training_date'), name='unique_training_per_date'),
        ),
    ]
